ERROR_VALIDATION_MESSAGE =                  "ERROR - An Error occurred while comparing between actual and expected request"
RESULTS_OF_TEST_MESSAGE =                   "The final result of the test : "
SET_CSV_FILE_MESSAGE =                      "Please enter a csv file path that include the test you request to run (pay attention insert the csv file without the csv suffix) \n, press ctrl+c to close"
START_TEST_MESSAGE =                        "Start of the test"
CLOSE_USER_SESSION =                        "Session user will now close"
SENT_FLASK_REQUEST =                        "sent flask request to engine"
SHUTDOWN_FUNCTION_NAME =                    'shutdown'
TEST_HAD_BEEN_FINISHED_FLASK =              " all the steps of the test had been finished see final results at the console "
NAME_OF_SERVER_WERKZUG =                    "werkzeug.server.shutdown"
SERVER_SHUT_DOWN_MESSAGE =                  "Server shutting down due to"
E_NODE_B_SENT_TO_ENGINE_REQUEST =           "cbsd sent request to engine from server"
INIT_TEST_DEFINITION =                      "init the test definition by the test steps sent from the user"
SUFFIX_OF_JSON_FILE =                       ".json"
COMPARING_JSONS_MESSAGE =                   "compare between requested json to expected json"
REQUEST_NODE_NAME =                         "Request"
RESPONSE_NODE_NAME =                        "response"
QUESTION_NODE_NAME =                        "questions"
HEART_BEAT_SUFFIX_HTTP =                    "heartbeat"
SPECTRUM_INQUIERY_SUFFIX_HTTP =             "spectrumInquiry"
HEART_BEAT_ARRIVED_MESSAGE =                "heartBeat request arrived to engine"
GRANT_SUFFIX_HTTP =                         "grant"
RELINQUISHMENT_SUFFIX_HTTP =                "relinquishment"
NSTEP_SESSION_WITH_TECHNITIAN =             "arrived to nstep starting question answer session with the technician"
HEARTBEAT_FROM_ENGINE_TO_CBSD_MESSAGE =      "return heart beat part of json from engine to the cbsd"
ADDITIONAL_COMMENTS_MESSAGE =               "the additional comments for the current test are : "
ANSWERS_NODE =                              "answers"
QUESTION_NODE =                             "question"
SUFFIX_NOT_EXISTS_IN_EXPECTED_JSON_FILE =   "ERROR - the suffix of the type of calling from http request is not exists in the expected json file from the csv"
HEART_BEAT_REACHED_TO_LIMIT_MESSAGE =       "ERROR - heartbeat had reached to the limit of heartbeat set from the config file"
HEART_BEAT_TIMEOUT_MESSAGE  =               "ERROR - the duration between the heartbeats are more then expected from json file"
EXPECT_ANSWER_NODE =                        "expectedAnswer"
CHOOSE_ONE_OF_THE_ANSWERS_MESSAGE =         " please choose one of the answers :"
LAST_STEP_TYPE =                            "nstep"
HEART_BEAT_REPEATS_SUFFIX =                 "Repeats"
ADD_TEST_TO_SPECIFIC_FOLDER_MESSAGE =       "would you like to add the test to specific folder ? (select yes or no)"
CLI_SESSION                        =        "CLISession"
GRANT_BEFORE_HEARTBEAT_ERROR       =        "ERROR - heartbeat request can be only after grant request"
SELECT_TO_ADD_TEST_MESSAGE         =        "you have choose to add the test "
SELECT_TO_ADD_FOLDER_MESSAGE    =           " to the specific folder :"
SELECTED_TEST_FROM_USER_MESSAGE =           "the selected test from the user : "
PASS_MESSAGE =                              "PASS"
FAIL_MESSAGE =                              "FAIL"
JSON_REQUEST_NOT_INCLUDE_KEY =              "ERROR - the http request does not include key : "
JSON_THIS_CBRS_STEPS_HAD_BEEN_FINISHED =    {
                                                "message" : "the specific cbrs had finished all steps successfully but the domain proxy still have cbrs that not finished all steps",
                                                "response": {
                                                    "responseCode": 0
                                                }
                                            }
REGISTRATION_SUFFIX_HTTP =                  "registration"
DEREGISTRATION_SUFFIX_HTTP =                "deregistration"
EMPTY_CSV_FILE_NAME_MESSAGE =               "cannot enter empty line for csv file try again"
ENTER_YES_OR_NO_MESSAGE =                   "valid input to the question is yes or no"
TYPE_NAME_OF_FOLDER      =                  "enter log of test to the specific folder"
VALIDATION_PASSED_MESSAGE =                 "validation passed successfully, the engine sent "
GOODBYE_MESSAGE =                           "The last test had been finished and no other csv file had been entered,  goodbye"
QUIT_PROGRAM_MESSAGE =                      "you decided to quit the program have a good day"